/* =========================================================================
 * Nodalis — service worker for the single-file build.
 *
 * Generated by tools/build.mjs. There is only one page and a handful of icons,
 * so the whole app is precached on install and served cache-first afterwards.
 * ========================================================================= */

const VERSION = 'nodalis-single-msvh6muo';
const SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icons/icon.svg',
  './icons/favicon-32.png',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(VERSION)
      .then((cache) => Promise.all(SHELL.map((url) =>
        // One missing file must not leave the whole app uncached.
        cache.add(new Request(url, { cache: 'reload' }))
          .catch((err) => console.warn('[sw] could not cache', url, err))
      )))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.map((k) => (k === VERSION ? null : caches.delete(k)))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  // Any navigation resolves to the single page, so deep links work offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('./index.html').then((hit) => hit || fetch(request).catch(() =>
        new Response(
          '<!DOCTYPE html><meta charset="utf-8"><title>Nodalis is offline</title>' +
          '<body style="font:16px/1.6 system-ui;padding:40px;max-width:520px;margin:0 auto;text-align:center">' +
          '<h1>Not cached yet</h1><p>Load Nodalis once while online and it will work offline from then on.</p>',
          { headers: { 'Content-Type': 'text/html; charset=utf-8' } }
        )
      ))
    );
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    // Only the optional OCR engine is third-party. Cache it opportunistically
    // so the second scan works with no connection.
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request).then((response) => {
        if (response && response.ok && /tesseract|tessdata/i.test(url.href)) {
          const copy = response.clone();
          caches.open(VERSION + '-ext').then((cache) => cache.put(request, copy));
        }
        return response;
      }).catch(() => new Response('', { status: 504, statusText: 'Offline' })))
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((response) => {
        if (response && response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(VERSION).then((cache) => cache.put(request, copy));
        }
        return response;
      }).catch(() => new Response('', { status: 504, statusText: 'Offline' }));
    })
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});
